

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class SwapChainPanel;
                ref class TextBlock;
                ref class Slider;
                ref class Button;
                ref class CheckBox;
                ref class AppBar;
            }
        }
    }
}

namespace KinectRecord
{
    partial ref class DirectXPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::SwapChainPanel^ swapChainPanel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ RecIndicator;
        private: ::Windows::UI::Xaml::Controls::Slider^ TimeSlider;
        private: ::Windows::UI::Xaml::Controls::Button^ PickAFileButton;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ FolderDisplay;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TakeDisplay;
        private: ::Windows::UI::Xaml::Controls::Button^ RecordButton;
        private: ::Windows::UI::Xaml::Controls::Button^ PlaybackButton;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ ColorCheckBox;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TakeDurationLabel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TakeDurationValue;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ FramesRecordedLabel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ FramesRecordedValue;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ FPSLabel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ FPSValue;
        private: ::Windows::UI::Xaml::Controls::AppBar^ bottomAppBar;
    };
}

